import { useState } from 'react';
import { 
  Search,
  Youtube,
  Facebook,
  HardDrive,
  FileText,
  FileType,
  Presentation,
  Music,
  Video,
  Image,
  Headphones,
  FileCode,
  File,
  Inbox,
  Loader2,
  X,
  ExternalLink
} from 'lucide-react';

interface SummaryTool {
  name: string;
  icon: React.ReactNode;
  color: string;
  type: string;
}

interface Summary {
  id: string;
  title: string;
  url: string;
  toolType: string;
  summary: string;
  createdAt: Date;
}

const DashboardPage = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [subjectName, setSubjectName] = useState('');
  const [selectedTool, setSelectedTool] = useState<SummaryTool | null>(null);
  const [summaries, setSummaries] = useState<Summary[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const summaryTools: SummaryTool[] = [
    { name: 'YouTube Summary', icon: <Youtube size={24} />, color: 'text-red-400', type: 'youtube' },
    { name: 'Facebook Summary', icon: <Facebook size={24} />, color: 'text-blue-400', type: 'facebook' },
    { name: 'Google Drive Summary', icon: <HardDrive size={24} />, color: 'text-yellow-400', type: 'google-drive' },
    { name: 'PDF Summary', icon: <FileText size={24} />, color: 'text-red-500', type: 'pdf' },
    { name: 'Article/Blog Summary', icon: <FileType size={24} />, color: 'text-purple-400', type: 'article' },
    { name: 'PPT/PPTX Summary', icon: <Presentation size={24} />, color: 'text-orange-400', type: 'ppt' },
    { name: 'Audio Summary', icon: <Music size={24} />, color: 'text-pink-400', type: 'audio' },
    { name: 'Video File Summary', icon: <Video size={24} />, color: 'text-cyan-400', type: 'video' },
    { name: 'Image Summary', icon: <Image size={24} />, color: 'text-green-400', type: 'image' },
    { name: 'Podcast Summary', icon: <Headphones size={24} />, color: 'text-indigo-400', type: 'podcast' },
    { name: 'TXT Summary', icon: <FileCode size={24} />, color: 'text-gray-400', type: 'txt' },
    { name: 'Other Summary', icon: <File size={24} />, color: 'text-blue-300', type: 'other' },
  ];

  const handleGenerateSummary = async (tool: SummaryTool) => {
    if (!subjectName.trim()) {
      alert('कृपया विषय का नाम दर्ज करें');
      return;
    }
    if (!searchQuery.trim()) {
      alert('कृपया URL या लिंक दर्ज करें');
      return;
    }

    setSelectedTool(tool);
    setIsGenerating(true);

    try {
      // TODO: Replace with actual API call
      // Simulating API call for now
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const newSummary: Summary = {
        id: Date.now().toString(),
        title: `${subjectName} - ${tool.name} - ${new Date().toLocaleDateString()}`,
        url: searchQuery,
        toolType: tool.type,
        summary: `This is a generated summary for the ${tool.name}. The content from ${searchQuery} has been processed and summarized using AI. This is a placeholder summary - in production, this would be generated by your AI backend service.`,
        createdAt: new Date()
      };

      setSummaries(prev => [newSummary, ...prev]);
      setSearchQuery('');
      setSubjectName('');
      setSelectedTool(null);
    } catch (error) {
      console.error('Error generating summary:', error);
      alert('Summary generate करने में त्रुटि हुई। कृपया पुनः प्रयास करें।');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleToolClick = (tool: SummaryTool) => {
    if (searchQuery.trim()) {
      handleGenerateSummary(tool);
    } else {
      setSelectedTool(tool);
    }
  };

  return (
    <div className="flex-1 flex flex-col overflow-auto bg-[#0a0a0a]">
      {/* Main Content */}
      <div className="flex-1 overflow-auto">
        <div className="max-w-7xl mx-auto px-6 py-8 space-y-8">
          {/* Top Search Bar - Integrated */}
          <div className="space-y-4">
            <div>
              <h1 className="text-3xl font-bold text-white mb-2">Summarizer Tools</h1>
              <p className="text-gray-400">Enter subject name and paste a URL to generate summaries</p>
            </div>
            
            <div className="bg-[#111111] border border-gray-800 rounded-xl p-4 space-y-4">
              <div className="relative">
                <input
  type="text"
  value={subjectName}
  onChange={(e) => setSubjectName(e.target.value)}
  placeholder="Enter subject name"
  className="w-full bg-[#1a1a1a] border border-gray-800 rounded-xl px-4 py-3.5 text-gray-100 placeholder-gray-500 focus:outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/30 transition-all"
  disabled={isGenerating}
/>
                {subjectName && (
                  <button
                    onClick={() => setSubjectName('')}
                    className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-200 transition-colors"
                  >
                    <X size={18} />
                  </button>
                )}
              </div>
              
              <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
                <div className="relative flex-1">
                  <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    onKeyPress={(e) => {
                      if (e.key === 'Enter' && selectedTool) {
                        handleGenerateSummary(selectedTool);
                      }
                    }}
                    placeholder="Search YouTube or paste any public URL"
                    className="w-full bg-[#1a1a1a] border border-gray-800 rounded-xl px-12 py-3.5 text-gray-100 placeholder-gray-500 focus:outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/30 transition-all"
                    disabled={isGenerating}
                  />
                  {searchQuery && (
                    <button
                      onClick={() => setSearchQuery('')}
                      className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-200 transition-colors"
                    >
                      <X size={18} />
                    </button>
                  )}
                </div>
                {searchQuery && selectedTool && !isGenerating && (
                  <button
                    onClick={() => handleGenerateSummary(selectedTool)}
                    className="px-6 py-3.5 bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600 text-white rounded-xl font-medium transition-all shadow-lg shadow-purple-500/20 hover:shadow-purple-500/30 flex items-center justify-center gap-2 whitespace-nowrap"
                  >
                    <Search size={18} />
                    <span>Generate Summary</span>
                  </button>
                )}
                {isGenerating && (
                  <button
                    disabled
                    className="px-6 py-3.5 bg-gradient-to-r from-purple-500 to-blue-500 text-white rounded-xl font-medium opacity-50 cursor-not-allowed flex items-center justify-center gap-2 whitespace-nowrap"
                  >
                    <Loader2 size={18} className="animate-spin" />
                    <span>Generating...</span>
                  </button>
                )}
              </div>
              {selectedTool && (
                <div className="mt-3 flex items-center gap-2 text-sm pt-3 border-t border-gray-800">
                  <span className="text-gray-400">Selected:</span>
                  <div className="flex items-center gap-2 px-3 py-1.5 bg-purple-500/20 border border-purple-500/30 rounded-lg">
                    <span className={selectedTool.color}>{selectedTool.icon}</span>
                    <span className="text-gray-200 font-medium">{selectedTool.name}</span>
                    <button
                      onClick={() => setSelectedTool(null)}
                      className="text-gray-400 hover:text-gray-200 transition-colors"
                    >
                      <X size={14} />
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
          {/* Summary Tools Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {summaryTools.map((tool, index) => (
              <button
                key={index}
                onClick={() => handleToolClick(tool)}
                disabled={isGenerating}
                className={`group relative bg-[#111111] border rounded-xl p-5 hover:border-purple-500/50 hover:bg-[#1a1a1a] transition-all duration-300 hover:shadow-lg hover:shadow-purple-500/20 hover:-translate-y-1 active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed ${
                  selectedTool?.type === tool.type
                    ? 'border-purple-500/50 bg-[#1a1a1a] ring-2 ring-purple-500/20'
                    : 'border-gray-800'
                }`}
              >
                {/* Hover Glow Effect */}
                <div className="absolute inset-0 bg-gradient-to-r from-purple-500/0 via-purple-500/10 to-blue-500/0 rounded-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                
                <div className="relative flex items-center space-x-4">
                  {/* Icon */}
                  <div className={`flex-shrink-0 p-3 rounded-lg bg-gray-800/50 group-hover:bg-gray-800 group-hover:scale-110 transition-all duration-300 ${tool.color}`}>
                    {tool.icon}
                  </div>
                  
                  {/* Title */}
                  <div className="flex-1 text-left">
                    <h3 className="text-sm font-semibold text-gray-100 group-hover:text-white transition-colors">
                      {tool.name}
                    </h3>
                  </div>
                </div>
              </button>
            ))}
          </div>

          {/* Recent Summaries Section */}
          <div className="mt-12">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-white">Recent Summaries</h2>
              {summaries.length > 0 && (
                <span className="text-sm text-gray-400">{summaries.length} summary(ies)</span>
              )}
            </div>

            {/* Summaries List or Empty State */}
            {summaries.length === 0 ? (
              <div className="bg-[#111111] border border-gray-800 rounded-xl p-12 text-center hover:border-gray-700 transition-colors">
                <div className="flex flex-col items-center justify-center space-y-4">
                  <div className="p-4 bg-gray-800/50 rounded-full">
                    <Inbox size={48} className="text-gray-600" />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-gray-200 mb-2">No summaries yet</h3>
                    <p className="text-gray-400 max-w-md">
                      पहले search bar में URL दर्ज करें, फिर एक summarizer tool चुनें
                    </p>
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                {summaries.map((summary) => {
                  const tool = summaryTools.find(t => t.type === summary.toolType);
                  return (
                    <div
                      key={summary.id}
                      className="bg-[#111111] border border-gray-800 rounded-xl p-6 hover:border-gray-700 transition-all hover:shadow-lg hover:shadow-purple-500/5"
                    >
                      <div className="flex items-start justify-between mb-4">
                        <div className="flex items-center gap-3 flex-1 min-w-0">
                          {tool && (
                            <div className={`flex-shrink-0 p-2 rounded-lg bg-gray-800/50 ${tool.color}`}>
                              {tool.icon}
                            </div>
                          )}
                          <div className="flex-1 min-w-0">
                            <h3 className="text-lg font-semibold text-white mb-1">{summary.title}</h3>
                            <div className="flex items-center gap-2 text-sm text-gray-400">
                              <span>{tool?.name}</span>
                              <span>•</span>
                              <span>{summary.createdAt.toLocaleDateString()}</span>
                            </div>
                          </div>
                        </div>
                        <a
                          href={summary.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex-shrink-0 p-2 text-gray-400 hover:text-purple-400 hover:bg-gray-800/50 rounded-lg transition-colors"
                          title="Open URL"
                        >
                          <ExternalLink size={18} />
                        </a>
                      </div>
                      <div className="bg-[#0a0a0a] border border-gray-800 rounded-lg p-4">
                        <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">
                          {summary.summary}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default DashboardPage;
